apiVersion: apps/v1
kind: Deployment
metadata:
  name: drweb-task
  namespace: drweb-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drweb-task
  template:
    metadata:
      labels:
        app: drweb-task
    spec:
      containers:
      - name: drweb-task
        image: skensel/drweb:{{CI_PIPELINE_ID}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8085