apiVersion: apps/v1
kind: Deployment
metadata:
  name: drweb
  namespace: drweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drweb
  template:
    metadata:
      labels:
        app: drweb
    spec:
      containers:
      - name: devops-test
        image: skensel/drweb:__VERSION__
        imagePullPolicy: Always
        ports:
        - containerPort: 8085