apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${NAME_PROJECT}
  namespace: ${NAME_PROJECT}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ${NAME_PROJECT}
  template:
    metadata:
      labels:
        app: ${NAME_PROJECT}
    spec:
      containers:
      - name: devops-test
        image: ${DOCKER_LOGIN}/${NAME_PROJECT}:${CI_PIPELINE_ID}
        imagePullPolicy: Always
        ports:
        - containerPort: 8085