apiVersion: v1
 kind: Deployment
 metadata:
   name: devops-test
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: devops-test
   template:
     metadata:
       labels:
         app: devops-test
     spec:
       containers:
       - name: devops-test
         image: ${DOCKER_LOGIN}/${NAME_PROJECT}:${CI_PIPELINE_ID}
         imagePullPolicy: Always
