apiVersion: v1
kind: Namespace
metadata:
  name: drweb-task
---
apiVersion: v1
kind: Service
metadata:
  name: drweb-task
  namespace: drweb-task
spec:
  type: LoadBalancer
  selector:
    app: drweb-task
  ports:
  - protocol: TCP
    nodePort: 30875
    port: 80
    targetPort: 8085
