apiVersion: v1
kind: Service
metadata:
  name: ${NAME_PROJECT}
  namespace: ${NAME_PROJECT}
spec:
  selector:
    app: ${NAME_PROJECT}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8085
  type: NodePort