apiVersion: v1
kind: Namespace
metadata:
  name: drweb-task
---
apiVersion: v1
kind: Service
metadata:
  name: drweb-task
  namespace: drweb-task
spec:
  selector:
    app: drweb-task
  ports:
  - protocol: TCP
    port: 80
  type: NodePort