apiVersion: v1
kind: Service
metadata:
  name: devops-test
  namespace: devops-test
spec:
  selector:
    app: devops-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8085
  type: NodePort